export const DOMAIN_TO_COMPANY: Record<string, string | null> = {
    // Tech giants
    'google.com': 'Google',
    'gmail.com': null, // Personal email
    'meta.com': 'Meta',
    'facebook.com': 'Meta',
    'instagram.com': 'Meta',
    'whatsapp.com': 'Meta',
    'apple.com': 'Apple',
    'microsoft.com': 'Microsoft',
    'amazon.com': 'Amazon',
    'netflix.com': 'Netflix',
    'salesforce.com': 'Salesforce',
    'oracle.com': 'Oracle',
    'adobe.com': 'Adobe',
    'ibm.com': 'IBM',
    'intel.com': 'Intel',
    'nvidia.com': 'NVIDIA',
    'amd.com': 'AMD',
    'qualcomm.com': 'Qualcomm',
    'cisco.com': 'Cisco',
    'vmware.com': 'VMware',

    // Startups & Tech
    'stripe.com': 'Stripe',
    'uber.com': 'Uber',
    'lyft.com': 'Lyft',
    'airbnb.com': 'Airbnb',
    'doordash.com': 'DoorDash',
    'instacart.com': 'Instacart',
    'square.com': 'Square',
    'plaid.com': 'Plaid',
    'coinbase.com': 'Coinbase',
    'robinhood.com': 'Robinhood',
    'chime.com': 'Chime',
    'figma.com': 'Figma',
    'notion.so': 'Notion',
    'slack.com': 'Slack',
    'zoom.us': 'Zoom',
    'dropbox.com': 'Dropbox',
    'asana.com': 'Asana',
    'atlassian.com': 'Atlassian',
    'gitlab.com': 'GitLab',
    'github.com': 'GitHub',
    'reddit.com': 'Reddit',
    'pinterest.com': 'Pinterest',
    'snap.com': 'Snap',
    'snapchat.com': 'Snap',
    'tiktok.com': 'TikTok',
    'bytedance.com': 'ByteDance',
    'twitter.com': 'Twitter',
    'x.com': 'X (Twitter)',

    // Venture Capital
    'a16z.com': 'Andreessen Horowitz',
    'sequoiacap.com': 'Sequoia Capital',
    'accel.com': 'Accel',
    'greylock.com': 'Greylock Partners',
    'benchmark.com': 'Benchmark',
    'kleinerperkins.com': 'Kleiner Perkins',
    'gv.com': 'Google Ventures',
    'nea.com': 'NEA',
    'foundry.com': 'Foundry Group',
    'spark.vc': 'Spark Capital',

    // Finance
    'gs.com': 'Goldman Sachs',
    'goldmansachs.com': 'Goldman Sachs',
    'jpmorgan.com': 'JPMorgan',
    'jpmchase.com': 'JPMorgan Chase',
    'morganstanley.com': 'Morgan Stanley',
    'citi.com': 'Citigroup',
    'baml.com': 'Bank of America',
    'blackrock.com': 'BlackRock',
    'vanguard.com': 'Vanguard',
    'fidelity.com': 'Fidelity',

    // Consulting
    'mckinsey.com': 'McKinsey & Company',
    'bain.com': 'Bain & Company',
    'bcg.com': 'Boston Consulting Group',
    'deloitte.com': 'Deloitte',
    'pwc.com': 'PwC',
    'ey.com': 'EY',
    'kpmg.com': 'KPMG',
    'accenture.com': 'Accenture',

    // AI Companies
    'openai.com': 'OpenAI',
    'anthropic.com': 'Anthropic',
    'deepmind.com': 'DeepMind',
    'huggingface.co': 'Hugging Face',
    'cohere.ai': 'Cohere',
    'stability.ai': 'Stability AI',
    'midjourney.com': 'Midjourney',
    'character.ai': 'Character.AI',

    // Personal email providers (ignore these)
    'yahoo.com': null,
    'hotmail.com': null,
    'outlook.com': null,
    'icloud.com': null,
    'me.com': null,
    'aol.com': null,
    'protonmail.com': null,
}
